# Generated by Django 3.2.9 on 2022-10-09 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_nr', models.IntegerField(blank=True, null=True, verbose_name='Nº de Autocarro')),
                ('spz', models.CharField(max_length=50, unique=True, verbose_name='Matrícula')),
                ('brand', models.CharField(blank=True, default='', max_length=50, verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperative', models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='Nome da Cooperativa')),
            ],
        ),
        migrations.CreateModel(
            name='Corridor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corridor', models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='Nome do Corridor')),
            ],
        ),
        migrations.CreateModel(
            name='Routa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routa', models.CharField(blank=True, default='', max_length=50, verbose_name='Nome da Routa')),
                ('via', models.CharField(blank=True, default='', max_length=50, verbose_name='Nome da Via')),
                ('corridor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routaCorridor', to='index_translation.corridor')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(blank=True, default='', max_length=100, unique=True, verbose_name='Gestor')),
                ('abbreviated', models.CharField(blank=True, default='', max_length=50, verbose_name='Nome Abreviado')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managerUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperativeR', models.CharField(blank=True, default='', max_length=100, verbose_name='Nome Da Cooperativa')),
                ('managerR', models.CharField(blank=True, default='', max_length=100, verbose_name='Nome do Gestor')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('activated', models.BooleanField(default=False, verbose_name='Atribuir')),
                ('bus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignBus', to='index_translation.bus')),
                ('cooperative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignCooperative', to='index_translation.cooperative')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignManager', to='index_translation.manager')),
            ],
        ),
    ]
