# Generated by Django 3.2.9 on 2021-11-22 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperative', models.CharField(blank=True, default='', max_length=50, verbose_name='Nome da Cooperativa')),
            ],
        ),
        migrations.CreateModel(
            name='Corridor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corridor', models.CharField(blank=True, default='', max_length=50, verbose_name='Nome do Corridor')),
            ],
        ),
        migrations.CreateModel(
            name='Routa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routa', models.CharField(blank=True, default='', max_length=50, verbose_name='Nome da Routa')),
                ('via', models.CharField(blank=True, default='', max_length=50, verbose_name='Nome da Via')),
                ('corridor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routaCorridor', to='index_translation.corridor')),
            ],
        ),
    ]
