# Generated by Django 3.2.9 on 2022-02-15 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index_translation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_nr', models.IntegerField(blank=True, null=True, verbose_name='Nº de Autocarro')),
                ('spz', models.CharField(max_length=50, unique=True, verbose_name='Matrícula')),
                ('brand', models.CharField(blank=True, default='', max_length=50, verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(blank=True, default='', max_length=50, verbose_name='Gestor')),
            ],
        ),
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('activated', models.BooleanField(default=False, verbose_name='Atribuir')),
                ('id_bus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignBus', to='index_translation.bus')),
                ('id_cooperative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignCooperative', to='index_translation.cooperative')),
                ('id_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignManager', to='index_translation.manager')),
            ],
        ),
    ]
