# Generated by Django 3.2.9 on 2022-02-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_translation', '0002_assign_bus_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='buses',
            field=models.ManyToManyField(to='index_translation.Bus'),
        ),
    ]
