# Generated by Django 3.2.9 on 2022-02-15 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_translation', '0004_auto_20220215_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='group',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='person',
        ),
        migrations.RemoveField(
            model_name='cooperative',
            name='buses',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
