# Generated by Django 3.2.9 on 2022-02-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_translation', '0005_auto_20220215_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assign',
            old_name='id_bus',
            new_name='bus',
        ),
        migrations.RenameField(
            model_name='assign',
            old_name='id_cooperative',
            new_name='cooperative',
        ),
        migrations.RenameField(
            model_name='assign',
            old_name='id_manager',
            new_name='manager',
        ),
        migrations.AddField(
            model_name='manager',
            name='abbreviated',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Nome Abreviado'),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='cooperative',
            field=models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='Nome da Cooperativa'),
        ),
        migrations.AlterField(
            model_name='corridor',
            name='corridor',
            field=models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='Nome do Corridor'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='operator',
            field=models.CharField(blank=True, default='', max_length=100, unique=True, verbose_name='Gestor'),
        ),
    ]
