# Generated by Django 3.2.9 on 2022-02-16 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_translation', '0006_auto_20220216_1100'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bus',
            unique_together={('spz',)},
        ),
    ]
