# Generated by Django 3.2.9 on 2022-02-16 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_translation', '0007_alter_bus_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bus',
            unique_together=set(),
        ),
    ]
