# Generated by Django 3.2.9 on 2022-02-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_translation', '0008_alter_bus_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign',
            name='cooperativeR',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nome Da Cooperativa'),
        ),
        migrations.AddField(
            model_name='assign',
            name='managerR',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nome do Gestor'),
        ),
    ]
