# Generated by Django 3.2.9 on 2022-01-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corridor_performance_report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corridor_performance_report',
            name='amount_ticket',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Receita de Tickets'),
        ),
    ]
