# Generated by Django 3.2.9 on 2022-10-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corridor_performance_report', '0002_alter_corridor_performance_report_spz'),
    ]

    operations = [
        migrations.AddField(
            model_name='corridor_performance_report',
            name='spz_1',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Matrícula'),
        ),
    ]
