# Generated by Django 3.2.9 on 2022-01-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corridor_performance_report', '0002_alter_corridor_performance_report_amount_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corridor_performance_report',
            name='amount_luggage',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Receita de Bagagem'),
        ),
        migrations.AlterField(
            model_name='corridor_performance_report',
            name='amount_ticket',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Receita de Tickets'),
        ),
        migrations.AlterField(
            model_name='corridor_performance_report',
            name='amt_income',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Receita da AMT'),
        ),
        migrations.AlterField(
            model_name='corridor_performance_report',
            name='luggage_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nº de Bagagem'),
        ),
        migrations.AlterField(
            model_name='corridor_performance_report',
            name='maxcom_income',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Receita da Maxcom'),
        ),
        migrations.AlterField(
            model_name='corridor_performance_report',
            name='operator_income',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Receita da Cooperativa'),
        ),
        migrations.AlterField(
            model_name='corridor_performance_report',
            name='passenger_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nº de Passageiros'),
        ),
        migrations.AlterField(
            model_name='corridor_performance_report',
            name='qr_ticket_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nº de Tickets'),
        ),
    ]
