# Generated by Django 3.2.9 on 2022-10-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corridor_performance_report', '0003_corridor_performance_report_spz_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='corridor_performance_report',
            name='line_nr_1',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Routa'),
        ),
    ]
