# Generated by Django 3.2.9 on 2022-02-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corridor_performance_report', '0004_auto_20220117_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corridor_performance_report',
            name='operator',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Gestor'),
        ),
        migrations.AlterField(
            model_name='corridor_performance_report',
            name='spz',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Matrícula'),
        ),
    ]
