# Generated by Django 3.2.9 on 2022-10-06 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corridor_performance_report', '0004_corridor_performance_report_line_nr_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corridor_performance_report',
            name='line_nr_1',
        ),
    ]
