# Generated by Django 3.2.9 on 2022-02-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductor_sales_report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor_sales_report',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30, verbose_name='Receita da Cooperativa'),
        ),
    ]
