# Generated by Django 3.2.9 on 2022-02-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductor_sales_report', '0002_alter_conductor_sales_report_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor_sales_report',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Cooperativa'),
        ),
        migrations.AlterField(
            model_name='conductor_sales_report',
            name='conductor_first_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='conductor_sales_report',
            name='conductor_last_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Gestor'),
        ),
    ]
