# Generated by Django 3.2.9 on 2022-03-07 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CSVS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_event',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='log_login',
            name='event_type',
            field=models.CharField(choices=[(0, 'out'), (1, 'in'), (2, 'timeout')], max_length=200, verbose_name='Tipo de Evento'),
        ),
        migrations.AlterField(
            model_name='log_login',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
