# Generated by Django 3.2.9 on 2022-03-07 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CSVS', '0002_auto_20220307_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_login',
            name='device_type',
            field=models.CharField(choices=[(1, 'android'), (2, 'ios'), (3, 'windowns'), (4, 'pc')], max_length=200, null=True, verbose_name='Tipo de Dispositivo'),
        ),
    ]
