# Generated by Django 3.2.9 on 2022-02-12 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CSVS', '0003_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv',
            name='file_row',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nº de Linhas'),
        ),
        migrations.AddField(
            model_name='csv',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Nome do Ficheiro'),
        ),
        migrations.AlterField(
            model_name='csv',
            name='file_name',
            field=models.FileField(upload_to='static/csvs', verbose_name='Ficheiro'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='emails',
            field=models.CharField(max_length=200, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=200, null=True, verbose_name='Nº de Telefone'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile1.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
