# Generated by Django 3.2.9 on 2022-02-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSVS', '0004_auto_20220212_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='name',
            field=models.CharField(blank=True, choices=[('Capacity summary report', 'Capacity summary report'), ('Conductor Sales Report', 'Conductor Sales Report'), ('Corridor performance report', 'Corridor performance report'), ('Passenger by bus and trip report', 'Passenger by bus and trip report'), ('Settlement file operator', 'Settlement file operator'), ('Cooperarive', 'Cooperarive'), ('Corridor', 'Corridor'), ('Routa', 'Routa')], default='', max_length=50, null=True, verbose_name='Nome do Ficheiro'),
        ),
    ]
