# Generated by Django 3.2.9 on 2022-02-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSVS', '0005_alter_csv_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Nome do Ficheiro'),
        ),
    ]
