# Generated by Django 3.2.9 on 2022-08-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSVS', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='file_name',
            field=models.FileField(upload_to='csvs', verbose_name='Ficheiro'),
        ),
    ]
