# Generated by Django 3.2.9 on 2022-10-09 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index_translation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='capacity_summary_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('bus_nr', models.IntegerField(blank=True, default='', verbose_name='Nº de Autocarro')),
                ('no_of_trips', models.IntegerField(blank=True, default='', verbose_name='Nº de Autocarro')),
                ('passenger_count', models.IntegerField(blank=True, default='', verbose_name='Nº de Autocarro')),
                ('total_income', models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30, verbose_name='Receita total')),
                ('maxcom_income', models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30, verbose_name='Receita da Maxcom')),
                ('amt_income', models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30, verbose_name='Receita da AMT')),
                ('operator_income', models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30, verbose_name='Receita da Cooperativa')),
                ('operator', models.CharField(blank=True, default='', max_length=50, verbose_name='Gestor')),
                ('cooperative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capacityCooperative', to='index_translation.cooperative')),
                ('corridor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capacityCorridor', to='index_translation.corridor')),
                ('line_nr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capacityRouta', to='index_translation.routa')),
                ('spz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capacityBus', to='index_translation.bus')),
            ],
        ),
    ]
