# Generated by Django 3.2.9 on 2022-07-12 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index_translation', '0003_alter_manager_user'),
        ('capacity_summary_report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacity_summary_report',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capacityManager', to='index_translation.manager'),
        ),
        migrations.AlterField(
            model_name='capacity_summary_report',
            name='spz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capacityBus', to='index_translation.bus'),
        ),
    ]
