# Generated by Django 3.2.9 on 2022-02-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacity_summary_report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacity_summary_report',
            name='amt_income',
            field=models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30, verbose_name='Receita da AMT'),
        ),
        migrations.AlterField(
            model_name='capacity_summary_report',
            name='maxcom_income',
            field=models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30, verbose_name='Receita da Maxcom'),
        ),
        migrations.AlterField(
            model_name='capacity_summary_report',
            name='operator_income',
            field=models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30, verbose_name='Receita da Cooperativa'),
        ),
        migrations.AlterField(
            model_name='capacity_summary_report',
            name='total_income',
            field=models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30, verbose_name='Receita total'),
        ),
    ]
