# Generated by Django 3.2.9 on 2022-02-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacity_summary_report', '0002_auto_20220211_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacity_summary_report',
            name='operator',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Gestor'),
        ),
        migrations.AlterField(
            model_name='capacity_summary_report',
            name='spz',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Matrícula'),
        ),
    ]
