# Generated by Django 3.2.9 on 2022-07-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacity_summary_report', '0002_auto_20220712_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacity_summary_report',
            name='operator',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Gestor'),
        ),
    ]
