# Generated by Django 3.2.9 on 2022-07-12 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index_translation', '0003_alter_manager_user'),
        ('capacity_summary_report', '0003_alter_capacity_summary_report_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacity_summary_report',
            name='spz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capacityBus', to='index_translation.bus'),
        ),
    ]
