# Generated by Django 3.2.9 on 2022-01-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='settlement_file_operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(blank=True, default='', max_length=50)),
                ('money_value', models.DecimalField(blank=True, decimal_places=3, default='', max_digits=7)),
                ('transaction_count', models.IntegerField(blank=True, default='')),
                ('money_value4', models.DecimalField(blank=True, decimal_places=3, default='', max_digits=7)),
                ('transaction_type2', models.IntegerField(blank=True, default='')),
                ('Textbox217', models.IntegerField(blank=True, default='')),
                ('Textbox214', models.IntegerField(blank=True, default='')),
                ('Textbox218', models.IntegerField(blank=True, default='')),
                ('transaction_count3', models.IntegerField(blank=True, default='')),
                ('Textbox74', models.DecimalField(blank=True, decimal_places=3, default='', max_digits=7)),
                ('Textbox88', models.DecimalField(blank=True, decimal_places=3, default='', max_digits=7)),
                ('transaction_count4', models.IntegerField(blank=True, default='')),
                ('Textbox98', models.DecimalField(blank=True, decimal_places=3, default='', max_digits=7)),
                ('Textbox100', models.DecimalField(blank=True, decimal_places=3, default='', max_digits=7)),
                ('rank', models.IntegerField(blank=True, default='')),
                ('carrier_name', models.CharField(blank=True, default='', max_length=50, verbose_name='Gestor da Cooperativa')),
                ('cooperatives', models.CharField(blank=True, default='', max_length=50, verbose_name='Nome da Cooperativa')),
                ('money_value3', models.DecimalField(blank=True, decimal_places=3, default='', max_digits=7, verbose_name='Receita da Cooperativa')),
                ('Textbox220', models.DecimalField(blank=True, decimal_places=3, default='', max_digits=7)),
                ('transaction_count2', models.DecimalField(blank=True, decimal_places=3, default='', max_digits=7)),
                ('Textbox76', models.DecimalField(blank=True, decimal_places=3, default='', max_digits=7)),
                ('Textbox77', models.DecimalField(blank=True, decimal_places=3, default='', max_digits=7)),
            ],
        ),
    ]
