# Generated by Django 3.2.9 on 2022-10-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='settlement_file_operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('transaction_type', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('money_value', models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30, null=True)),
                ('transaction_count', models.IntegerField(blank=True, default='', null=True)),
                ('money_value4', models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30, null=True)),
                ('transaction_type2', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('Textbox217', models.IntegerField(blank=True, default='', null=True)),
                ('Textbox214', models.IntegerField(blank=True, default='', null=True)),
                ('Textbox218', models.IntegerField(blank=True, default='', null=True)),
                ('transaction_count3', models.IntegerField(blank=True, default='', null=True)),
                ('Textbox74', models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30, null=True)),
                ('Textbox88', models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30, null=True)),
                ('transaction_count4', models.IntegerField(blank=True, default='', null=True)),
                ('Textbox98', models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30, null=True)),
                ('Textbox100', models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30, null=True)),
                ('rank', models.IntegerField(blank=True, default='', null=True)),
                ('carrier_name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Gestor')),
                ('cooperatives', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Cooperativa')),
                ('money_value3', models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30, null=True, verbose_name='Receita da Cooperativa')),
                ('Textbox220', models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30, null=True)),
                ('transaction_count2', models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30, null=True)),
                ('Textbox76', models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30, null=True)),
                ('Textbox77', models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30, null=True)),
            ],
        ),
    ]
