# Generated by Django 3.2.9 on 2022-02-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement_file_operator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement_file_operator',
            name='Textbox100',
            field=models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30),
        ),
        migrations.AlterField(
            model_name='settlement_file_operator',
            name='Textbox220',
            field=models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30),
        ),
        migrations.AlterField(
            model_name='settlement_file_operator',
            name='Textbox74',
            field=models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30),
        ),
        migrations.AlterField(
            model_name='settlement_file_operator',
            name='Textbox76',
            field=models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30),
        ),
        migrations.AlterField(
            model_name='settlement_file_operator',
            name='Textbox77',
            field=models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30),
        ),
        migrations.AlterField(
            model_name='settlement_file_operator',
            name='Textbox88',
            field=models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30),
        ),
        migrations.AlterField(
            model_name='settlement_file_operator',
            name='Textbox98',
            field=models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30),
        ),
        migrations.AlterField(
            model_name='settlement_file_operator',
            name='money_value',
            field=models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30),
        ),
        migrations.AlterField(
            model_name='settlement_file_operator',
            name='money_value3',
            field=models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30, verbose_name='Receita da Cooperativa'),
        ),
        migrations.AlterField(
            model_name='settlement_file_operator',
            name='money_value4',
            field=models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30),
        ),
        migrations.AlterField(
            model_name='settlement_file_operator',
            name='transaction_count2',
            field=models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30),
        ),
    ]
