# Generated by Django 3.2.9 on 2022-07-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement_file_operator', '0002_auto_20220726_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement_file_operator',
            name='cooperatives',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Cooperativa'),
        ),
    ]
