# Generated by Django 3.2.9 on 2022-07-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement_file_operator', '0004_remove_settlement_file_operator_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement_file_operator',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
    ]
