# Generated by Django 3.2.9 on 2022-07-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement_file_operator', '0005_settlement_file_operator_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement_file_operator',
            name='Textbox100',
            field=models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='settlement_file_operator',
            name='Textbox214',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='settlement_file_operator',
            name='Textbox217',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='settlement_file_operator',
            name='Textbox218',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='settlement_file_operator',
            name='Textbox220',
            field=models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='settlement_file_operator',
            name='Textbox74',
            field=models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='settlement_file_operator',
            name='Textbox76',
            field=models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='settlement_file_operator',
            name='Textbox77',
            field=models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='settlement_file_operator',
            name='Textbox88',
            field=models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='settlement_file_operator',
            name='Textbox98',
            field=models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='settlement_file_operator',
            name='carrier_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Gestor'),
        ),
        migrations.AlterField(
            model_name='settlement_file_operator',
            name='cooperatives',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Cooperativa'),
        ),
        migrations.AlterField(
            model_name='settlement_file_operator',
            name='money_value',
            field=models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='settlement_file_operator',
            name='money_value3',
            field=models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30, null=True, verbose_name='Receita da Cooperativa'),
        ),
        migrations.AlterField(
            model_name='settlement_file_operator',
            name='money_value4',
            field=models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='settlement_file_operator',
            name='rank',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='settlement_file_operator',
            name='transaction_count',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='settlement_file_operator',
            name='transaction_count2',
            field=models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='settlement_file_operator',
            name='transaction_count3',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='settlement_file_operator',
            name='transaction_count4',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='settlement_file_operator',
            name='transaction_type',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='settlement_file_operator',
            name='transaction_type2',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
