# Generated by Django 3.2.9 on 2022-07-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement_file_operator', '0006_auto_20220727_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement_file_operator',
            name='transaction_type2',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
