# Generated by Django 3.2.9 on 2021-11-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger_by_bus_and_trip_report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger_by_bus_and_trip_report',
            name='route_reg_no',
            field=models.IntegerField(blank=True, default='', verbose_name='Direcção do Autocarro'),
        ),
        migrations.AlterField(
            model_name='passenger_by_bus_and_trip_report',
            name='route_reg_no1',
            field=models.IntegerField(blank=True, default='', verbose_name='Direcção do Autocarro'),
        ),
    ]
