# Generated by Django 3.2.9 on 2022-07-26 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index_translation', '0003_alter_manager_user'),
        ('passenger_by_bus_and_trip_report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger_by_bus_and_trip_report',
            name='spz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passengerBus', to='index_translation.bus'),
        ),
    ]
