# Generated by Django 3.2.9 on 2022-02-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger_by_bus_and_trip_report', '0002_auto_20211122_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger_by_bus_and_trip_report',
            name='money_value',
            field=models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30, verbose_name='Valor Pago'),
        ),
        migrations.AlterField(
            model_name='passenger_by_bus_and_trip_report',
            name='money_value1',
            field=models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30, verbose_name='Total do valor pago'),
        ),
        migrations.AlterField(
            model_name='passenger_by_bus_and_trip_report',
            name='money_value3',
            field=models.DecimalField(blank=True, decimal_places=3, default='', max_digits=30, verbose_name='Total de transações diárias'),
        ),
    ]
